# Настройки подключения к БД
db:
  host: "localhost"
  port: 27017
  name: "database"
  collection: "documents"

logic:
  delay: 1.0
  error_delay: 30.0
  target_docs: 70000
  user_agent: "robby"
  
data:
  source_dir: "./corpus_arxiv_html"

  source_name: "ar5iv.org"
